### ISSUE TITLE
Conflicting Faraday requirements

### ISSUE THREAD

**Issue by seydar** [ccjr/alpaca-trade-api#15]
The requirement for an old version of Faraday from 2018 is preventing me from using other libraries that require Faraday ~> 1.0.1 (I'm using plivo to send texts).

`~/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/rubygems/specification.rb:2243:in `raise_if_conflicts': Unable to activate plivo-4.16.0, because faraday-0.17.4 conflicts with faraday (~> 1.0.1) (Gem::ConflictError)`

It *looks* like the only fix is a gemfile upgrade, since the calls to Faraday are pretty straightforward.

**Comment by ccjr** [comment]
Version `0.7.0` is out, it has support for Faraday `1.x`.
