### ISSUE TITLE
trail_percent: and trail_price: are not supported

### ISSUE THREAD

**Issue by fluffyx** [ccjr/alpaca-trade-api#20]
Impossible to make a trailing_stop order as documented here: https://alpaca.markets/docs/api-documentation/api-v2/orders/

```
client.new_order side: :sell, symbol: symbol, qty: 100,
                 type: :trailing_stop, trail_percent: percent, time_in_force: :day
```

**Comment by ccjr** [comment]
This is a community driven project, please issue a PR. It should be fairly easy to implement, here's a recent example: https://github.com/ccjr/alpaca-trade-api/pull/17
