### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by gamesover** [ccjr/alpaca-trade-api#25]
I can see api v1 is deprecated and v2 [PR](https://github.com/ccjr/alpaca-trade-api/pull/22) was pending for a long time.

If owner is not interested in maintaining the project anymore, I'd like to join as a new contriburtor.

Kindly offer me the authrization :)

Thanks :)

**Comment by ccjr** [comment]
I'm getting back to the project, I'll get to that PR soon. A PR was merged a few days ago - https://github.com/ccjr/alpaca-trade-api/pull/23 - and I have a new one - https://github.com/ccjr/alpaca-trade-api/pull/24. I'm happy to add anyone who has contributed as a maintainer.

**Comment by gamesover** [comment]
Glad to see @ccjr continue to maintain the project.

You can do it :)
