### ISSUE TITLE
BigDecimal Issue 

### ISSUE THREAD

**Issue by adebnar** [ccjr/alpaca-trade-api#8]
Hey I wanted to let you know that I received an error when running bars 

`.rvm/gems/ruby-2.7.1/gems/alpaca-trade-api-0.4.0/lib/alpaca/trade/api/bar.rb:11:in `initialize': undefined method `BigDecimal' for #<Alpaca::Trade::Api::Bar:0x000fb6dba0> (NoMethodError)
`
I added `require 'bigdecimal'` to correct the issue. 

However now when I run bars the return value is not displaying correctly. I am using 
   alpaca-trade-api (0.4.0)
      faraday (~> 0.15)
    bigdecimal (1.4.4)
The return value looks like this for "LUV"
`@time=2020-04-24 14:45:00 -0500, @open=0.2948e2, @high=0.2951e2, @low=0.29455e2, @close=0.2949e2, @volume=10556`

Am I missing something I saw that you pushed an update to correct the decimal issue.

Thanks

**Comment by ccjr** [comment]
Hi, I've just run into that now. I'll get a fix in asap.

**Comment by ccjr** [comment]
I released a fix as https://rubygems.org/gems/alpaca-trade-api/versions/0.4.1.
